export const GET_NEWS_REQUEST = "GET_NEWS_REQUEST";
export const ADD_NEWS_REQUEST = "ADD_NEWS_REQUEST";
export const DELETE_NEWS_REQUEST = "DELETE_NEWS_REQUEST";
export const GET_FULL_NEWS_REQUEST = "GET_FULL_NEWS_REQUEST";

export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const ADD_NEWS_SUCCESS = "ADD_NEWS_SUCCESS";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const GET_FULL_NEWS_SUCCESS = "GET_FULL_NEWS_SUCCESS";

export const GET_NEWS_FAILURE = "GET_NEWS_FAILURE";
export const ADD_NEWS_FAILURE = "ADD_NEWS_FAILURE";
export const DELETE_NEWS_FAILURE = "DELETE_NEWS_FAILURE";
export const GET_FULL_NEWS_FAILURE = "GET_FULL_NEWS_FAILURE";

export const ADD_NEWS_INIT = "ADD_NEWS_INIT";
export const FULL_NEWS_INIT = "FULL_NEWS_INIT";

export const COMMENT_REQUEST = "COMMENT_REQUEST";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const COMMENT_FAILURE = "COMMENT_FAILURE";
export const COMMENTS_INIT = "COMMENTS_INIT";